<!--用户基础信息-->
select ACCS_NBR_MD5,CUST_SERVICE_LEVEL,MEMBERSHIP_LEVEL,GENDER,CUST_STATE_NAME,AGE
,CREDIT_LEVEL,OPEN_DATE,UNINSTALL_DATE,ONLINE_DUR,CUST_POINT,ADD_POINT,PAYMENT_MODE_NAME
from INTEG_USER_INFO_MASK_M
<!--用户账务信息-->
select ACCS_NBR_MD5,MONTH_ID,PAY_CHARGE,PAY_TIMES,MAX_PAY_METHOD,BILL_AMT,LATE_AMT
from INTEG_USER_ACCT_MASK_M
<!--号码状态变化-->
select ACCS_NBR_MD5,CHGCARD_TIMES,PREUNINSTALL_TIMES,INITSTOP_TIMES,LAST_PASSSTOP1_DATE
,LAST_N_PASSSTOP1_DATE,PASSSTOP1_TIMES,LAST_PASSSTOP2_DATE,LAST_N_PASSSTOP2_DATE
,PASSSTOP2_TIMES from INTEG_USER_STATECHG_MASK_D
<!--移动语音-->
select MSISDN,CALL_TYPE,CFEE,LFEE,BILLING_MODE,CALL_DURATION,LONG_TYPE,START_TIME
,END_TIME from phone_voice_detail
<!--移动上网数据-->
select MSISDN,CALL_TYPE,BASIC_FEE,FEE_ADD,BILLING_MODE,START_TIME,END_TIME
from phone_data_detail


select INTEG_USER_INFO_MASK_M.ACCS_NBR_MD5,CUST_SERVICE_LEVEL,MEMBERSHIP_LEVEL,GENDER
,CUST_STATE_NAME,AGE,CREDIT_LEVEL,OPEN_DATE,UNINSTALL_DATE,ONLINE_DUR,CUST_POINT
,ADD_POINT,PAYMENT_MODE_NAME
,CHGCARD_TIMES,PREUNINSTALL_TIMES,INITSTOP_TIMES,LAST_PASSSTOP1_DATE
,LAST_N_PASSSTOP1_DATE,PASSSTOP1_TIMES,LAST_PASSSTOP2_DATE,LAST_N_PASSSTOP2_DATE
,PASSSTOP2_TIMES
,MONTH_ID,PAY_CHARGE,PAY_TIMES,MAX_PAY_METHOD,BILL_AMT,LATE_AMT
from INTEG_USER_INFO_MASK_M left outer join INTEG_USER_STATECHG_MASK_D on
INTEG_USER_INFO_MASK_M.ACCS_NBR_MD5 = INTEG_USER_STATECHG_MASK_D.ACCS_NBR_MD5
left outer join INTEG_USER_ACCT_MASK_M on
INTEG_USER_INFO_MASK_M.ACCS_NBR_MD5 = INTEG_USER_ACCT_MASK_M.ACCS_NBR_MD5
left outer join (select t.MSISDN,t.CALL_TYPE as voice_CALL_TYPE,t.CFEE as voice_CFEE
,t.LFEE as voice_LFEE,t.BILLING_MODE,CALL_DURATION,LONG_TYPE
from phone_voice_detail as t  group by substr(START_TIME,0,6)) a on